name: Deployment Prod #lerolero
on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Package upload
        run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging 
      - name: SonarQube Scan
        id: sonarqube-scan
        uses: sonarsource/sonarqube-scan-action@master        
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: Upload test report in case of failure # reporte por si falla
        if: failure() && steps.sonarqube-scan.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test.json      
      - name: Continue if SonarQube scan passed
        #if: ${{ success() }}
        # if: success() && steps.sonarqube-scan.outcome == 'success'
        if: steps.sonarqube-scan.outcome == 'success'
        run: echo "SonarQube scan passed. Continue with the pipeline."
      
      #- name: Debug SonarQube scan outputs
      #  run: |
      #    echo "SonarQube scan status: ${{ steps.sonarqube-scan.outputs.status }}" 
      #- name: Continue if SonarQube scan passed
      #  if: ${{ steps.sonarqube-scan.outputs.status == 'Success' }}
      #  run: echo "SonarQube scan passed. Continue with the pipeline."
      
#      - name: Build and analyze
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
#        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar